apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: knative-webhook-kinesis-http
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: ghcr.io/rfaircloth-splunk/knative-webhook-kinesis-http:v1.0.5
          volumeMounts:
            - name: webhook-signing
              mountPath: "/app/.certs"
              readOnly: true
      volumes:
        - name: webhook-signing
          secret:
            secretName: webhook-signing
