apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: knative-webhook-kinesis-http
  namespace: default
  labels:
    app.kubernetes.io/name: webhook-kinesis-http
    app.kubernetes.io/version: ghcr.io/rfaircloth-splunk/knative-webhook-kinesis-http:v1.0.11
    app.kubernetes.io/component: front-end
    app.kubernetes.io/part-of: webhook-gateway
spec:
  template:
    spec:
      containers:
        - image: ghcr.io/rfaircloth-splunk/knative-webhook-kinesis-http:v1.0.11
          volumeMounts:
            - name: webhook-signing
              mountPath: "/app/.certs"
              readOnly: true
      volumes:
        - name: webhook-signing
          secret:
            secretName: webhook-signing
