apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: knative-webhook-kinesis-http
  namespace: default
  labels:
    app.kubernetes.io/name: webhook-kinesis-http
    app.kubernetes.io/version: ghcr.io/rfaircloth-splunk/knative-webhook-kinesis-http:v
    app.kubernetes.io/component: front-end
    app.kubernetes.io/part-of: webhook-gateway
    app:
      kubernetes.io/version: ghcr.io/rfaircloth-splunk/knative-webhook-kinesis-http:v1.0.7
spec:
  template:
    spec:
      containers:
        - image: ghcr.io/rfaircloth-splunk/knative-webhook-kinesis-http:v1.0.7
          volumeMounts:
            - name: webhook-signing
              mountPath: "/app/.certs"
              readOnly: true
      volumes:
        - name: webhook-signing
          secret:
            secretName: webhook-signing
metadata\:
  labels\:
    app\:
      kubernetes\:
        io/version: ghcr.io/rfaircloth-splunk/knative-webhook-kinesis-http:v
